config/routes.rb
Rails.application.routes.draw do

  root "companies#index"
  resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :title, presence: true
	validates :description, presence: true
	has_many :employees, dependent: :destroy
	accepts_nested_attributes_for :employees,reject_if: :all_blank, allow_destroy: true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def index
  	@companies=Company.all
  end

  def new
  	@company=Company.new
  	@company.employees.build
  end

	def create
		@company=Company.new(company_params)
  	if @company.save
     redirect_to @company, notice: 'Company was successfully created.'
   	else
   		render :new
  	end
 	end

  
  def show
  	@company=Company.find(params[:id])
  end

  def edit
  	@company=Company.find(params[:id])
  	@company.employees.build
  end

  def update
  	@company=Company.find(params[:id])
  	if @company.update(company_params)
  		redirect_to @company, notice: 'Details successfully updated.'
  	else
  		render :edit
  	end
  end

  def destroy
  	@company=Company.find(params[:id])
  	@company.delete
  	redirect_to root_path, notice: 'All traces of company removed'
  end

  private 
  	def company_params
  		params.require(:company).permit(:title, :description, employees_attributes: [:id, :name, :_destroy])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_employee_fields.html.erb
	<div class="nested-fields"> <%= f.label :name%>
	<%= f.text_field :name%>
		
	<%= link_to_remove_association "Remove", f %></div><br>

app/views/companies/edit.html.erb
<h2>Edit Comapny Name or Add Employees</h2>

<%= form_for @company, html: {mutipart: true}  do | f |%>
  
  <%= f.label :title%>
  <%= f.text_field :title %>
  <h3>Employees</h3>
  <%= f.fields_for :employees do | emp |%>
  	<%= render 'employee_fields', f: emp%>
  	<br>
  <%end%>
  <div><%=link_to_add_association 'Add Employee', f, :employees%></div>
  <%= f.submit %></td>
<%end%>

app/views/companies/index.html.erb
<p class = "notice"><%= notice %></p>

<%@companies.each do |c|%>
<div class ="links">
	<h1><%= c.title %> </h1>
	<span class ="bold"><%= link_to "Employees List", company_path(c)%></span>
	<span class ="bold"><%= link_to "Add/Edit Employees", edit_company_path(c)%></span>
	<span class ="bold"><%= link_to "Delete", c, method: :delete, data: {confirm: "Are you sure?? All employee records will be deleted"}%></span>
</div>
<%end%>

app/views/companies/new.html.erb
<h1>Add Company</h1>
<% if @company.errors.any?%>
	<% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
  <% end %>
<%end%>

<%= form_for @company, html: {mutipart: true}  do | f |%>
  
  <%= f.label :title%>
  <%= f.text_field :title %>

  <%= f.label :description%>
  <%= f.text_field :description %>
  <h3>Employees</h3>
  <%= f.fields_for :employees do | emp |%>
  	<%= render 'employee_fields', f: emp%>
  	<div><%=link_to_add_association 'Add Employee', f, :employees%></div><br>
  <%end%>
  
  <%= f.submit %></td>
<%end%>

app/views/companies/show.html.erb
<p  class = "notice"><%= notice %></p>
<h1><%= @company.title%>
<small>:::<%= @company.description%></small></h1>
<table>
	<tr>
		<th width = 200px>Employee Id</th>
		<th width = 230px, align = "left">Employee Name</th>
	</tr>
	<% @company.employees.each do |ce|%>
	<tr>
		<td align = "center">
			<%=ce.id%> 
		</td>
		<td align = "left">
			<%=ce.name%>
		</td>
	</tr>
	<%end%>
</table>

<p><%= link_to "Edit/Add Employees", edit_company_path(@company)%></p>

app/views/layouts/_links.html.erb
<div class = "links">
	<button><%= link_to "New Company", new_company_path%> </button>
	<button><%= link_to "All Companies", root_path%></button>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Session141TableRelationships</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/links'%>
	<div class = "wrapper">
		<p>Create two tables. Company and Employee. Add the following relationships :
 Company has many employees and Employee belongs to company <br> Display the Employees in the company page </p>
		<%= yield %>
	</div>

</body>
</html>